### PR TITLE
Remove Windows Thumbnail Cache

### PR DESCRIPTION
**Pull request by Mailaender**
Put it in your local `.gitignore` afterwards.

### CODE REVIEW

**Comment by alessandrofrancesconi** [comment]
Why don't ignore Thumbs.db for all folders?

**Comment by Mailaender** [comment]
Yes, for all folders. But it is platform specific.

**Comment by alessandrofrancesconi** [comment]
Closed as I've added more exclusions in a single commit 
https://github.com/alessandrofrancesconi/gimp-plugin-bimp/commit/dd98731b6043fbd05a7f5fdcc1621d4fd1a37fc0

**Comment by Mailaender** [comment]
https://github.com/alessandrofrancesconi/gimp-plugin-bimp/blob/master/src/images/Thumbs.db is still there!

**Comment by alessandrofrancesconi** [comment]
Done! Thank you. Changing gitignore is not enough

**Pull request closed without merging**
