### PR TITLE
Overhaul GUI to improve flexibility and high DPI support

### LINKED ISSUE #101: HiDPI support
screenshot from 2016-01-05 13-03-47
screenshot from 2016-01-05 13-03-35

It's a bit difficult to read on a 2x device_pixel_ratio on Gnome Shell 3.18.3

### LINKED ISSUE #204: Plugin Window Resizing Windows 10
Window will not resize, minimize or maximize on Windows 10 (Gimp 2.10.8)
BIMP window

### PR DESCRIPTION
**Pull request by scribblemaniac**
Changes are mostly to make GUI elements display properly on devices that have scaling applied (as is the case with many high-dpi displays). The resize dialog was redesigned to be more streamlined. Many small tweaks were made to some of the windows to improve their aesthetic and consistency. Some of the GUI code was refactored to reduce the amount of redundant code.

There is room for improvement in high DPI support, however it relies upon GTK+3 features, which will not be available until GIMP v3.0 is released. I have included some commented out code that will serve as a good place to start when improving this with GTK+3.

Fixes #101 
Fixes #204 

| Before | After|
|----|-----|
| main_before | main_after |
| preview_before | preview_after |
|  changeformat_before | changeformat_after |
| color_before | color_after |
| crop_before | crop_after |
| fliprotate_before | fliprotate_after |
| rename_before | rename_after |
| resize_before | resize_after |
| sharpblur_before | sharpblur_after |
| userdef_before | userdef_after |
| watermark_before | watermark_after |

### CODE REVIEW

**Comment by alessandrofrancesconi** [comment]
Thank you really much for this, glad someone has taken some time to fix the HDPI issue!

I also see some changes in the watermark code, this does not seem to be related to the DPI scaling. I will test it on my dev soon, meanwhile you should explain what's changed.
Also, your watermark update seems to affect the serialization part, I think it needs to be updated in order to save/restore the new resize_mode_width/resize_mode_height param:
https://github.com/alessandrofrancesconi/gimp-plugin-bimp/blob/master/src/bimp-serialize.c#L569
https://github.com/alessandrofrancesconi/gimp-plugin-bimp/blob/master/src/bimp-serialize.c#L585

**Comment by scribblemaniac** [comment]
The watermark code change was the refactoring I was referring to. I changed it so that the GUI buttons for it could be generated and saved in a loop rather than nine nearly identical large chunks of code and it just made sense to number them way I did at the time. You're right that it affects the serialization, I will fix that soon, probably by going back to the original numbering. I assume you meant to refer to the watermark position rather than the resize_mode_width/resize_mode_height, which I already updated the save/restore for here:
https://github.com/alessandrofrancesconi/gimp-plugin-bimp/pull/213/files#diff-5e131012e00fe51fb8b20eeaa1ec344fR198-R199
https://github.com/alessandrofrancesconi/gimp-plugin-bimp/pull/213/files#diff-5e131012e00fe51fb8b20eeaa1ec344fR231-R258

The GUI changes should be pretty self-explanatory from the images. The only other non-GUI changes that I can think of were to the resize mode as you've already noticed. The plugin currently allows you to "Set to a percentage of the original" or "Set exact size in pixel for both dimensions/width/height". The new dialog provides the same options by changing the unit, and additional new combinations of options such as only setting the width/height in percent, or setting one in percent and the the other in pixels, or even setting neither (which could still be useful if you just want to set the resolution). These new options had to be saved, and the operations had to be updated to support them. I tried to test all of the possible combinations and this seems to work reasonably in all cases now.

Sorry i know I could have broken all this up better into separate commits, but I just wasn't thinking about that at the time.

**Comment by alessandrofrancesconi** [comment]
So I'm trying your changes in my Win10 x64 with GIMP 2.10.12.
I think there is something still missing for the size of the dialogs and widgets:

This is what I see right when opening BIMP:
immagine

And this is after resizing the window. I think it is just a matter of giving a "100%" width to the folder selector widget.
immagine

This is what happen when passing a very long folder name. You should give a fixed of at least a maximum width to that button:
immagine

The manipulation dialogs are Ok apart from the "Other GIMP procedure...". Maybe it just needs to have a larger default width:
immagine

**Comment by alessandrofrancesconi** [comment]
The Watermark code seems to work fin instead ;)

**Comment by scribblemaniac** [comment]
> And this is after resizing the window. I think it is just a matter of giving a "100%" width to the folder selector widget.

This is intentional. The input files are full file paths while the output folder is only the folder name, so the input file will benefit more from a larger width.

> This is what happen when passing a very long folder name. You should give a fixed of at least a maximum width to that button:

*No fixed sizes!* That's how the GUI got all messed up in the first place. I agree though that there needs to be a limit on the width of that button. Unfortunately there isn't any simple way to do that in GTK, but I'll see what I can work out.

> The manipulation dialogs are Ok apart from the "Other GIMP procedure...". Maybe it just needs to have a larger default width:

The challenge with this dialog is that the procedure can be arbitrarily large (gimp-context-set-paint-mode is a good example of this). That's why there's a scroll option, and why resizing that window will give all of the new space to the right-hand panel. It starts out at the minimum size, but I will make it wider by default if that's what you want.

**Pull request merged**
